---
- name: Ticket validation and Project Sync
  hosts: all
  gather_facts: True
  tasks:
 
    - name: validate ticket
      include_role:
       name: ticket_check

    - name: update project
      include_role:
       name: project_update 
      when: valid_rep == "1"

    - name: failed
      include_role:
       name: failed
      when: valid_rep == "0"
