---
- hosts: localhost
  gather_facts: false

  tasks:

   - name: Validate ticket
     uri:
       url: "https://192.168.1.20/api/v2/users/?username={{ticket_id}}"
       method: GET
       user: admin
       password: redhat
       validate_certs: False
       force_basic_auth: yes
     register: ticket_resp

   - name: user valid
     set_fact:
       valid_rep: "{{ticket_resp.json.count }}" 

   - name: Excute Project sync if ticket_id valid
     block:
      - name: API call to validate value
        uri:
          url: "https://192.168.1.20/api/v2/projects/?name={{project_name}}"
          method: GET
          user: admin
          password: redhat
          validate_certs: False
          force_basic_auth: yes
        register: api_output

        set_fact:
          project_id: "{{ api_output.json.results[0].id }}"

      - name: Project sync
        uri:
          url: https://192.168.1.20/api/v2/projects/{{project_id}}/update/
          method: POST
          user: admin
          password: redhat
          validate_certs: False
          force_basic_auth: yes
          status_code: 202
     when: valid_rep == "1"

   - name: Ticket is not valid
     fail:
       msg: This ticket is not valid
     when: valid_rep == "0"  
