- name: Validate ticket
  uri:
    url: "https://192.168.1.20/api/v2/users/?username={{ticket_id}}"
    method: GET
    user: admin
    password: redhat
    validate_certs: False
    force_basic_auth: yes
  register: ticket_resp

- name: user valid
  set_fact:
    valid_rep: "{{ticket_resp.json.count }}" 
