- name: Validate ticket example (DEMO needs to be change with endusers ticket api) 
  uri:
    url: "https://{{ansible_nodename}}/api/v2/users/?username={{ticket_id}}"
    method: GET
    user: "{{ tower_api_user }}"
    password: "{{ tower_api_pass }}"
    validate_certs: False
    force_basic_auth: yes
  register: ticket_resp

- name: user valid
  set_fact:
    valid_rep: "{{ticket_resp.json.count }}" 
