- name: API call to validate value
  uri:
    url: "https://192.168.1.20/api/v2/projects/?name={{project_name}}"
    method: GET
    user: admin
    password: redhat
    validate_certs: False
    force_basic_auth: yes
  register: api_output

-  set_fact:
     project_id: "{{ api_output.json.results[0].id }}"

- name: Project sync
  uri:
    url: https://192.168.1.20/api/v2/projects/{{project_id}}/update/
    method: POST
    user: admin
    password: redhat
    validate_certs: False
    force_basic_auth: yes
    status_code: 202
  register: prosync


- name:
  debug:
    var: prosync
